[package]
name = "dpf"
version = "0.1.0"
edition = "2021"
description = "A Rust crate providing DPF operations implemented in C++"
license = "MIT"

[lib]
name = "dpf"
path = "rust/lib.rs"

[dependencies] 